package com.nask.agent.llm;

import org.springframework.stereotype.Component;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Deterministic development implementation of {@link LlmGateway}.
 *
 * <p>The stub proves the runtime, persistence, approval, and audit loop without
 * depending on external model credentials. Replacing it with a real gateway
 * should keep the same method contracts.</p>
 */
@Component
@ConditionalOnProperty(name = "agent.llm.provider", havingValue = "stub", matchIfMissing = true)
public class StubLlmGateway implements LlmGateway {
    /**
     * Produces a simple task understanding from the raw request text.
     */
    @Override
    public TaskUnderstanding understandTask(TaskContext context) {
        return new TaskUnderstanding(
                context.userRequest(),
                inferType(context.userRequest()),
                List.of("Only operate inside the trusted workspace", "Keep changes small and auditable"),
                searchHints(context.userRequest()));
    }

    /**
     * Returns a fixed three-step plan used by the Phase 1 MVP.
     */
    @Override
    public PlanDraft createPlan(PlanningContext context) {
        return new PlanDraft(List.of(
                new PlanDraft.Item("Inspect workspace files", List.of(), "List files and capture workspace shape"),
                new PlanDraft.Item("Create an auditable task note", List.of("AGENT_TASK_NOTE.md"), "Stub implementation records task intent without changing source code"),
                new PlanDraft.Item("Validate with an approved command if available", List.of(), "Validation is routed through command policy")));
    }

    /**
     * Maps the fixed plan item descriptions to local tool actions.
     */
    @Override
    public AgentDecision decideNextAction(ExecutionContext context) {
        var description = context.currentItem().description().toLowerCase(Locale.ROOT);
        if (description.contains("inspect")) {
            return new AgentDecision(context.currentItem().id(), List.of(
                    new AgentDecision.Action("LIST_FILES", "Understand workspace structure", Map.of("path", ".", "maxDepth", 4))));
        }
        if (description.contains("note")) {
            return new AgentDecision(context.currentItem().id(), List.of(
                    new AgentDecision.Action("CREATE_FILE", "Record the auditable task intent for the MVP stub loop",
                            Map.of("path", "AGENT_TASK_NOTE.md", "content", "# Agent Task Note\n\nThis file was created by the phase 1 StubLlmGateway to prove the audited file-change loop.\n"))));
        }
        return new AgentDecision(context.currentItem().id(), List.of());
    }

    @Override
    public PlanDraft replan(ExecutionContext context, String failureSummary) {
        return new PlanDraft(List.of(new PlanDraft.Item(
                "Recover from runtime failure: " + failureSummary,
                context.currentItem().relatedFiles(),
                "Generated by stub recovery path")));
    }

    /**
     * Suggests a portable JVM smoke command as validation.
     */
    @Override
    public ValidationDecision suggestValidation(ValidationContext context) {
        return new ValidationDecision(true, List.of("java", "-version"), "Run a portable JVM smoke validation command");
    }

    /**
     * Builds a minimal Markdown report draft.
     */
    @Override
    public FinalReportDraft generateReport(ReportContext context) {
        return new FinalReportDraft("""
                # Agent Run Report

                ## Task

                %s

                ## Result

                %s
                """.formatted(context.taskSummary(), context.resultSummary()));
    }

    /**
     * Infers a coarse task type from common keywords.
     */
    private String inferType(String userRequest) {
        var lower = userRequest.toLowerCase(Locale.ROOT);
        if (lower.contains("bug") || lower.contains("fix") || lower.contains("修复")) {
            return "BUG_FIX";
        }
        if (lower.contains("test") || lower.contains("测试")) {
            return "TEST";
        }
        return "CODE_EDIT";
    }

    /**
     * Extracts short search hints from the request text.
     */
    private List<String> searchHints(String userRequest) {
        var hints = new ArrayList<String>();
        for (var token : userRequest.split("\\s+")) {
            var normalized = token.replaceAll("[^A-Za-z0-9_.$-]", "");
            if (normalized.length() >= 4) {
                hints.add(normalized);
            }
            if (hints.size() >= 5) {
                break;
            }
        }
        return hints;
    }
}
