package com.nask.agent.report;

import com.nask.agent.audit.AuditService;
import com.nask.agent.common.Domain;
import com.nask.agent.conversation.ConversationService;
import com.nask.agent.file.FileChangeRepository;
import com.nask.agent.git.GitToolService;
import com.nask.agent.llm.LlmGateway;
import com.nask.agent.memory.ProjectMemoryRepository;
import com.nask.agent.runtime.RuntimeFailureService;
import com.nask.agent.task.CodingTask;
import com.nask.agent.workspace.Workspace;
import com.nask.agent.workspace.WorkspaceService;
import com.nask.agent.workflow.WorkflowService;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class ReportServiceTests {
    @Test
    void fallsBackToDeterministicNarrativeWhenReportModelFails() {
        var repository = mock(TaskReportRepository.class);
        var fileChanges = mock(FileChangeRepository.class);
        var audit = mock(AuditService.class);
        var failures = mock(RuntimeFailureService.class);
        var workflows = mock(WorkflowService.class);
        var memory = mock(ProjectMemoryRepository.class);
        var conversations = mock(ConversationService.class);
        var workspaces = mock(WorkspaceService.class);
        var git = mock(GitToolService.class);
        var llm = mock(LlmGateway.class);
        var service = new ReportService(repository, fileChanges, audit, failures, workflows, memory,
                conversations, workspaces, git, llm);
        var task = task();

        when(fileChanges.findByTask(task.id())).thenReturn(List.of());
        when(audit.eventsForTask(task.id())).thenReturn(List.of());
        when(failures.findByTask(task.id())).thenReturn(List.of());
        when(workflows.nodes(task.id())).thenReturn(List.of());
        when(workflows.edges(task.id())).thenReturn(List.of());
        when(memory.findProfileByWorkspace(task.workspaceId())).thenReturn(Optional.empty());
        when(memory.findMemoryRetrievalsByRun(task.id())).thenReturn(List.of());
        when(memory.findMemoryWriteProposalsByRun(task.id())).thenReturn(List.of());
        when(conversations.previousTaskContext(task.conversationId(), task.id(), 5)).thenReturn(List.of());
        when(workspaces.getRequired(task.workspaceId())).thenReturn(workspace(task.workspaceId()));
        when(git.inspectWorkspaceStatus(any(), any()))
                .thenReturn(new GitToolService.GitWorkspaceStatus(true, "clean", List.of(), List.of()));
        when(llm.generateReport(any())).thenThrow(new IllegalStateException("model unavailable"));
        when(repository.insert(any(TaskReport.class))).thenAnswer(invocation -> invocation.getArgument(0));

        var report = service.generate(task, task.id(), "Task completed.");

        assertThat(report.contentMd())
                .contains("# Result")
                .contains("Task completed.")
                .contains("Report narration could not be generated by the model")
                .contains("## Runtime Details");
    }

    private CodingTask task() {
        var now = Instant.parse("2026-05-23T00:00:00Z");
        return new CodingTask(UUID.randomUUID(), UUID.randomUUID(), null, 1, "task", "检查README",
                Domain.TaskStatus.COMPLETED.name(), "REVIEW", now, now, null, Map.of(), now, now);
    }

    private Workspace workspace(UUID id) {
        return new Workspace(id, "test", ".", true, List.of(), List.of(), List.of(), Instant.now(), Instant.now());
    }
}
